import Link from "next/link";
import type { ReactNode } from "react";
import { ArrowRight, BookOpen, Calculator, CheckCircle2, GitCompareArrows, HeartPulse, ShieldCheck, Sparkles } from "lucide-react";
import { Container } from "@/components/ui/Container";

function SectionIntro({ eyebrow, title, description }: { eyebrow: string; title: string; description?: string }) {
  return <div className="section-intro"><p className="section-eyebrow">{eyebrow}</p><h2>{title}</h2>{description && <p className="mt-3 max-w-2xl text-base leading-7 text-slate-400">{description}</p>}</div>;
}

export function PepExplains() {
  return <section className="pep-story-section py-16 sm:py-24" aria-labelledby="explains-title"><Container width="wide"><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr] lg:items-center"><SectionIntro eyebrow="Pep explica" title="De una pregunta a una respuesta que puedes revisar" description="Pep estructura cada conversación para que entiendas el concepto, el nivel de evidencia y los límites de lo que se sabe." /><div className="response-story"><div className="story-question"><span className="story-label">Tu pregunta</span><p>¿Qué debería revisar antes de comparar dos péptidos?</p></div><div className="story-connector"><span /><ArrowRight className="h-4 w-4" /><span /></div><div className="story-answer"><div className="flex items-center gap-2"><span className="pep-mini-dot" />Pep AI <span className="story-status">Respuesta educativa</span></div><h3 className="mt-4 text-xl font-semibold text-white">Comparamos mecanismo, evidencia y seguridad.</h3><div className="mt-4 grid gap-3 sm:grid-cols-3"><div><p className="context-label">Evidencia</p><p className="mt-1 text-xs leading-5 text-slate-400">Qué tan sólida es la información.</p></div><div><p className="context-label">Seguridad</p><p className="mt-1 text-xs leading-5 text-slate-400">Qué límites conviene conocer.</p></div><div><p className="context-label">Fuentes</p><p className="mt-1 text-xs leading-5 text-slate-400">Dónde revisar el contexto.</p></div></div><div className="mt-5 flex flex-wrap gap-2"><Link href="/aviso-medico" className="story-link"><ShieldCheck className="h-3.5 w-3.5" />Ver seguridad</Link><Link href="/peptidos" className="story-link"><BookOpen className="h-3.5 w-3.5" />Abrir biblioteca</Link></div></div></div></div></Container></section>;
}

export function PepToolsFlow() {
  const steps = [["Pregunta", "Escribes lo que quieres entender", Sparkles], ["Pep entiende", "Ordena intención y contexto", HeartPulse], ["Activa una herramienta", "Biblioteca, comparación o cálculo", Calculator], ["Resultado revisable", "Respuesta con límites y fuentes", CheckCircle2]] as const;
  return <section className="border-y border-white/[0.06] bg-[#0b1e32]/55 py-16 sm:py-24" aria-labelledby="tools-flow-title"><Container width="wide"><SectionIntro eyebrow="Pep usa herramientas" title="La conversación puede llevarte más lejos" description="Pep no es una caja negra: conecta tu pregunta con el recurso apropiado y te deja continuar explorando." /><div className="tool-flow mt-10">{steps.map(([title, description, Icon], index) => <div className="tool-flow-step" key={title}><div className="tool-flow-icon"><Icon className="h-5 w-5" /></div><div><p className="text-sm font-semibold text-white">{title}</p><p className="mt-1 text-sm leading-6 text-slate-400">{description}</p></div>{index < steps.length - 1 && <ArrowRight className="tool-flow-arrow" aria-hidden />}</div>)}</div><div className="mt-8 flex flex-wrap gap-3"><Link href="/calculadoras" className="button-secondary"><Calculator className="h-4 w-4" />Abrir calculadoras</Link><Link href="/donde-comprar" className="button-secondary"><HeartPulse className="h-4 w-4" />Revisar proveedores</Link><Link href="/aprende" className="button-secondary"><BookOpen className="h-4 w-4" />Leer ciencia</Link></div></Container></section>;
}

export function PepContext() {
  return <section className="pep-context-section py-16 sm:py-24" aria-labelledby="context-title"><Container width="wide"><div className="context-panel context-panel-rich"><div className="max-w-xl"><p className="section-eyebrow">Pep muestra el contexto</p><h2 id="context-title" className="mt-2 text-3xl font-semibold tracking-tight text-white sm:text-4xl">No sólo respuestas. Mejores preguntas.</h2><p className="mt-4 text-base leading-7 text-slate-300">Cada respuesta debe ayudarte a distinguir lo que se sabe, lo que se discute y lo que todavía necesita más evidencia.</p></div><div className="context-response"><div className="flex items-center gap-2 text-xs text-cyan-200"><CheckCircle2 className="h-4 w-4" />Contexto incluido en la respuesta</div><div className="context-response-grid mt-5"><div><p className="context-label">Evidencia</p><p className="mt-2 text-sm text-slate-300">Limitada, moderada o sólida según la fuente disponible.</p></div><div><p className="context-label">Seguridad</p><p className="mt-2 text-sm text-slate-300">Riesgos, límites y cuándo consultar a un profesional.</p></div><div><p className="context-label">Regulación</p><p className="mt-2 text-sm text-slate-300">Aprobado, investigacional, off-label o no aprobado.</p></div><div><p className="context-label">Fuentes</p><p className="mt-2 text-sm text-slate-300">Enlaces para revisar el contexto por ti mismo.</p></div></div></div></div></Container></section>;
}

export function FinalChatCta({ workspace }: { workspace: ReactNode }) {
  return <section className="final-chat-section border-t border-white/[0.06] py-16 sm:py-24" aria-labelledby="final-cta-title"><Container width="narrow"><div className="text-center"><div className="final-pep-mark"><Sparkles className="h-5 w-5" /></div><h2 id="final-cta-title" className="mt-5 text-3xl font-semibold tracking-tight text-white sm:text-4xl">¿Qué quieres entender ahora?</h2><p className="mx-auto mt-3 max-w-lg text-slate-400">La conversación continúa cuando tengas tu próxima pregunta.</p></div><div className="mt-8">{workspace}</div></Container></section>;
}

export const comparisonIcon = GitCompareArrows;
